stages:
  - build
  - deploy

nuoyis_image_tag:
  image: ubuntu:24.04
  stage: build
  except:
    - build.json
    - README.md
  script:
    - echo "Changing to domestic mirrors for faster package installation"
    - sed -i 's|http://archive.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
    - sed -i 's|http://security.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
    - apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false update -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false upgrade -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false install -y ca-certificates  # 更新源列表
    - apt-get install -y git curl build-essential jq  # 安装常用工具，如 git, curl 等
    - current_version=$(jq -r '.version' build.json)
    - IFS='.' read -ra version_parts <<< "$current_version"
    - ((version_parts[2]++))
    - new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
    - echo "VERSION=$new_version" > nuoyis.env
  artifacts:
    paths:
      - nuoyis.env
  only: 
    - main

nuoyis_image_build:
  image: ubuntu:24.04
  timeout: 10 hours
  stage: deploy
  dependencies:
    - nuoyis_image_tag
  before_script:
  - sed -i 's|http://archive.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
  - sed -i 's|http://security.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
  - apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false update -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false upgrade -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false install -y ca-certificates  # 更新源列表
  - apt-get update && apt-get install -y curl jq git docker.io qemu-user-static binfmt-support
  - export DOWNLOAD_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce"
  - curl -fsSL https://study-download.nuoyis.net/github/https://raw.githubusercontent.com/docker/docker-install/master/install.sh | sh
  - docker --version
  - docker buildx version
  - mkdir -p /etc/buildkit/
  - cat > /etc/buildkit/buildkitd.toml<< EOF
        [registry."docker.io"]
          mirrors = [
          "https://hub.nastool.de",
          "https://docker.1ms.run",
          "https://docker.1panel.live",
          "https://docker.1panel.top",
          "https://hub-mirror.c.163.com",
          "https://mirror.baidubce.com",
          "https://dockerhub.icu",
          "https://hub.rat.dev",
          "https://docker.wanpeng.top",
          "https://docker.mrxn.net",
          "https://docker.anyhub.us.kg",
          "https://dislabaiot.xyz",
          "https://docker.fxxk.dedyn.io",
          "https://docker-mirror.aigc2d.com",
          "https://doublezonline.cloud",
          "https://dockerproxy.com",
          "https://mirror.iscas.ac.cn",
          "https://docker66ccff.lovablewyh.eu.org",
          "https://docker.m.daocloud.io"
        ]
    EOF
  - docker buildx create --name multi-builder --driver docker-container --config /etc/buildkit/buildkitd.toml --use
  - docker buildx inspect --bootstrap
  - chmod +x build.sh
  script:
    - export $(cat nuoyis.env | xargs)
    - echo "构建版本号 $VERSION"
    - REGISTRY_URL="registry.cn-hangzhou.aliyuncs.com"
    - IMAGE_NAME="nuoyis/nuoyis-lnmp"
    - IMAGE_MULTI="$REGISTRY_URL/$IMAGE_NAME:$VERSION"
    - IMAGE_LIST="\
      ${IMAGE_MULTI}-linux-amd64 \
      ${IMAGE_MULTI}-linux-arm64 \
      ${IMAGE_MULTI}-linux-arm-v7"
    - bash build.sh 2 $VERSION
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $REGISTRY_URL
    - echo "创建 manifest 并打标签"
    - docker buildx imagetools create -t "$IMAGE_MULTI" $IMAGE_LIST
    - docker tag "$IMAGE_MULTI" "$REGISTRY_URL/$IMAGE_NAME:latest"
    - docker push "$REGISTRY_URL/$IMAGE_NAME:latest"
    - jq ".version = \"$VERSION\"" build.json > temp.json
    - mv temp.json build.json
    - git config user.name "nuoyis"
    - git config user.email "wkkjonlykang@vip.qq.com"
    - git remote rm origin
    - git remote add origin http://oauth2:$GitLab_Access_Tokens@192.168.223.1:2236/nuoyis/nuoyis-lnmp-np.git
    - git add build.json
    - git commit -m "use to $VERSION"
    - git push origin HEAD:main -o ci.skip
  only:
    - main
