stages:
  - build
  - deploy

nuoyis_image_tag:
  image: ubuntu:24.04
  stage: build
  except:
    - build.json
    - README.md
  script:
    - echo "Changing to domestic mirrors for faster package installation"
    - sed -i 's|http://archive.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
    - sed -i 's|http://security.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
    - apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false update -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false upgrade -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false install -y ca-certificates  # 更新源列表
    - apt-get install -y git curl build-essential jq  # 安装常用工具，如 git, curl 等
    - current_version=$(jq -r '.version' build.json)
    - IFS='.' read -ra version_parts <<< "$current_version"
    - ((version_parts[2]++))
    - new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
    - echo "VERSION=$new_version" > nuoyis.env
  artifacts:
    paths:
      - nuoyis.env
  only: 
    - main

nuoyis_image_build:
  image: ubuntu:24.04
  timeout: 10 hours
  stage: deploy
  dependencies:
    - nuoyis_image_tag
  before_script:
  - sed -i 's|http://archive.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
  - sed -i 's|http://security.ubuntu.com|https://mirrors.huaweicloud.com|g' /etc/apt/sources.list.d/ubuntu.sources
  - apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false update -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false upgrade -y && apt-get -o Acquire::https::Verify-Peer=false -o Acquire::https::Verify-Host=false install -y ca-certificates  # 更新源列表
  - apt-get update && apt-get install -y curl jq git docker.io qemu-user-static binfmt-support
  - export DOWNLOAD_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce"
  - curl -fsSL https://study-download.nuoyis.net/github/https://raw.githubusercontent.com/docker/docker-install/master/install.sh | sh
  - docker --version
  - docker buildx version
  - mkdir -p /etc/buildkit/
  - cp ./buildkitd.toml /etc/buildkit/
  - docker run --rm --privileged docker.m.daocloud.io/tonistiigi/binfmt --install all
  - docker buildx create --name mybuilder --driver docker-container --config /etc/buildkit/buildkitd.toml --use
  - docker buildx inspect --bootstrap
  - chmod +x build.sh
  script:
    - export $(cat nuoyis.env | xargs)
    - echo "构建版本号 $VERSION"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
    - bash build.sh 2 $VERSION
    - jq ".version = \"$VERSION\"" build.json > temp.json
    - mv temp.json build.json
    - git config user.name "nuoyis"
    - git config user.email "wkkjonlykang@vip.qq.com"
    - git remote rm origin
    - git remote add origin http://oauth2:$GitLab_Access_Tokens@192.168.223.1:2236/nuoyis/nuoyis-lnmp-np.git
    - git add build.json
    - git commit -m "use to $VERSION"
    - git push origin HEAD:main -o ci.skip
  only:
    - main
